---
- hosts: webAppServerGroup
  become: true  
  tasks:
  - name: Deploy app on tomcat 
    maven_artifact:
      group_id: mvn_group
      artifact_id: v0.0
      version: 1.0-SNAPSHOT
      extension: war
      repository_url: http://192.168.1.33:8081/nexus/repository/pipeline0/
      dest: /usr/share/tomcat/webapps/pilot_porj_0.war
    notify: tomcat_restart
      
  handlers:
    - name: tomcat_restart
      service: name=tomcat state=started
